@startuml
title WatermelonDB Sync Flow

actor User

participant "ReactApp+WatermelonDB" as ReactApp
participant BackendApp
database ServerDB

User -> ReactApp : click Sync\n(or auto sync)
activate ReactApp

autonumber

ReactApp -> ReactApp : ""synchronize()""
activate ReactApp #Yellow

ReactApp -> ReactApp : ""pullChanges(lastPulledAt)""
activate ReactApp #OrangeRed

ReactApp -> BackendApp : ""GET pull(lastPulledAt)""
activate BackendApp

BackendApp -> ServerDB : get ""changes"" \n& ""timestamp""
ServerDB -> BackendApp : ""changes"" \n& ""timestamp""

BackendApp -> ReactApp : ""changes"" \n& ""timestamp""
deactivate BackendApp

ReactApp -> ReactApp : apply ""changes"" on localDB
ReactApp -> ReactApp : for next pull, set\n""lastPulledAt"" = ""timestamp""

deactivate ReactApp

ReactApp -> ReactApp : ""pushChanges(changes,""\n""lastPulledAt)""
activate ReactApp #DeepSkyBlue

ReactApp -> BackendApp : ""POST push(lastPulledAt,""\n""changes)""
activate BackendApp

BackendApp -> ServerDB : check conflict\nusing ""lastPulledAt""
ServerDB -> BackendApp

BackendApp -> ServerDB : if no conflict,\nrecord ""changes""
ServerDB -> BackendApp

BackendApp -> ReactApp
deactivate ReactApp

deactivate BackendApp

autonumber stop

ReactApp -> User
deactivate ReactApp

@enduml